### ISSUE TITLE
How does this comapre with Live preview?

### ISSUE THREAD

**Issue by aloisdg** [urin/vscode-web-visual-editor#1]
> Preview your HTML files quickly by clicking the preview button in the top right corner of your editor or using the context menu.

![](https://raw.githubusercontent.com/microsoft/vscode-livepreview/main/img/open-preview-btn.gif)

https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server

**Comment by urin** [comment]
I have updated the [README](https://github.com/urin/vscode-web-visual-editor?tab=readme-ov-file#alternatives) to address it.
