### ISSUE TITLE
Can't install it in Cursor due to version checks

### ISSUE THREAD

**Issue by gchokov** [urin/vscode-web-visual-editor#2]
Could it work with Cursor?
<img width="274" alt="Screenshot 2024-10-14 at 13 37 00" src="https://github.com/user-attachments/assets/02056256-904f-4d37-9cef-a57f0e36dbc1">

**Comment by urin** [comment]
Please follow [Update vscode version \- Cursor Community Forum](https://forum.cursor.com/t/update-vscode-version/15467).
Supported VSCode version is [1.92](https://github.com/urin/vscode-web-visual-editor/blob/main/package.json#L14).
