### ISSUE TITLE
[Request] Add vscode-web-visual-editor to open-vsx.org

### ISSUE THREAD

**Issue by noonsleeper** [urin/vscode-web-visual-editor#3]
Would you consider adding this extension to https://open-vsx.org/ then will be available to be used by projects like https://github.com/VSCodium/vscodium/

**Comment by urin** [comment]
Done 😃 
[Web Visual Editor – Open VSX Registry](https://open-vsx.org/extension/Urin/vscode-web-visual-editor)

**Comment by noonsleeper** [comment]
Thanks! =)
