### ISSUE TITLE
[Request]: Need a way to open Dev Tools Pane

### ISSUE THREAD

**Issue by mbennette68** [urin/vscode-web-visual-editor#4]
Hi,

Is there a way to open a Dev Tools Pane similar to the below image taken from another extension. 
If not this would be a useful feature to add so that JavaScript console.log() output can be seen.
![dev_tools_pane_2024-10-14 21-42-25](https://github.com/user-attachments/assets/040fae65-75ba-4f16-9521-a85298bfc933)

I also suggest that the Tool Bar (highlighted in green below) of the Visual Web Editor should have the ability to be hidden and/or moved to the other side:

![dev_tools_pane_2024-10-14 22-03-25_2](https://github.com/user-attachments/assets/5c670fd6-efef-4ea2-bdae-5844132f34ff)

Thank you,
MB

**Comment by urin** [comment]
Please create other issue for toolbar enhancement.

**Comment by mbennette68** [comment]
Ok,

New issue has been created :)

**Comment by urin** [comment]
> Is there a way to open a Dev Tools Pane similar to the below image taken from another extension.

I don't know how to do that. Which specific extension are you referring to?

**Comment by mbennette68** [comment]
Hello,

Refer to the following image for labels. The other extension is called, "**_Live Preview,_** boxed in Lavander or Pink color." Clicking on the **_hamburger_**, boxed in green will reveal the option, **_Open Devtool Pane_**, boxed in Light Blue color. Clicking on that will activate the _**Dev Tools Pane**_, boxed in Red Color. 

Basically, it's just like _**Right-Clicking**_ on a Firefox page and choosing, _**Inspect**_.

It's just difficult on most of the tools that have this features to easily access the _**Inspect**_ functionality of browsers.
It should be just easy as a keyboard short cut or _**Right-Clicking**_ on the live preview page.

![vs_codium_cropped_2024-10-19 12-39-01](https://github.com/user-attachments/assets/93d73b25-27a9-432e-8e94-683dcfabcc55)

Thank you,
MB

**Comment by urin** [comment]
VS Code includes a built-in developer tool accessible directly from the application.
To open it, go to the top menu bar, select `Help > Toggle Developer Tools`.
This will launch the Chrome DevTools window.

![{18A32634-3527-46A8-8F52-704016A7E279}](https://github.com/user-attachments/assets/7fc854fb-78ec-438c-b5f0-3310a6e5b7bc)

**Comment by mbennette68** [comment]
Urin,

Thank you for the information. I'd forgotten that option. I was just curious to see if 
there was an easier way to bring up the Dev Tools function, for example, by toggling  
it from within your extension, perhaps with a right-click, or keyboard short cut, or a 
button, something quicker than always having to go to the help menu. 

Thank you for your input.
MB :)

**Comment by urin** [comment]
As a result of the investigation, I’ve decided not to implement it because it would require significant changes. If a method for this is provided through the VSCode API in the future, I’ll reopen this issue and consider implementing it.
