### ISSUE TITLE
 [Request]: Toolbar Enhancement (hide or move)

### ISSUE THREAD

**Issue by mbennette68** [urin/vscode-web-visual-editor#5]
I suggest that the Tool Bar (highlighted in green below) of the Visual Web Editor should have the ability to be hidden and/or moved. As is, for some devices (e.g. laptops) with small screen it takes up much needed viwing real estate:
![dev_tools_pane_2024-10-14 22-03-25_2](https://github.com/user-attachments/assets/66ab17fa-6e70-4cca-8c29-aed28d773801)

Thank you,
MB

**Comment by urin** [comment]
I plan to add a settings feature to the extension in the near future.

**Comment by urin** [comment]
[I added an option to control element movement](https://github.com/urin/vscode-web-visual-editor/commit/1bd0076ef3670d64eb6b91b42c3ac9635456a744), but decided not to implement functionality to control the toolbar’s visibility and position. The reasons are:

- A Refresh button is necessary to reflect changes when image files or other resources are updated.
- Moving the toolbar to the right offers little advantage.
