### ISSUE TITLE
Can't run it in VSCodium

### ISSUE THREAD

**Issue by AtmanActive** [urin/vscode-web-visual-editor#8]
Hi,

I can't get this extension to run on VSCodium v1.91.1 on windows,

- Tried installing from VSIX v0.1.5, - silent fail.
- Tried installing from extensions pane inside VSCodium, version on offer is v0.1.2 - got the message "Can't install •urin.vscode-web-visual-editor• extension because it is not compatible with the current version of VSCodium (version 1.91.1)."

Thanks.

**Comment by urin** [comment]
Refer [VSCodium releases](https://github.com/vscodium/vscodium/releases) and update it.
Supported VSCode version is [1.92](https://github.com/urin/vscode-web-visual-editor/blob/main/package.json#L14).
It seems that lowering the supported version on Microsoft Marketplace is not possible.
You can also work around this by unpacking the .vsix file, modifying the "engine" in the package.json, and then repackaging it.

**Comment by AtmanActive** [comment]
Yes.
I upgraded my VSCodium to v1.95.2 and now the extension is loading correctly.

Thank you!
