### ISSUE TITLE
Similar Extension

### ISSUE THREAD

**Issue by jogibear9988** [urin/vscode-web-visual-editor#9]
There is another similar extension:

https://github.com/node-projects/vs-code-designer-addon
https://marketplace.visualstudio.com/items?itemName=node-projects.vscode-designer-addon

It offers also Stylesheet parsing, webcomponent support, resize, transform etc support, ....

**Comment by urin** [comment]
[node\-projects/vs\-code\-designer\-addon](https://github.com/node-projects/vs-code-designer-addon) may not be actively maintained. It supports Web Components only in limited environments, and the webpage language is restricted to English, so its versatility is low.
[Web Vistual Editor](https://github.com/urin/vscode-web-visual-editor) has minimized dependencies, offers high versatility, and supports stylesheets.

**Comment by jogibear9988** [comment]
thats not correct, it is maintained.

- it supports sync of selection to designer, means if you select something in the text editor it's reflected in the designer
- It has property editors
- It can resize elements
- Elements can be dragged around
- It supports correct overlays for multiple transformed elements. means if they are rotaed, skewed, ...
- It supports adding new elements
- Supports SVG Editing

**Comment by urin** [comment]
Yes, that extension certainly implements many features.
Web Visual Editor selectively includes only essential features, making the codebase lightweight.
